### ISSUE TITLE
[Docs] github action으로 테스트 코드 적용하는 방식 찾아보고 정리

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-Code-Analysis-Server#136]
## 📝 Description
**무엇을?**
-  github action으로 테스트 코드 적용하는 방식 찾아보고 정리

**왜?**
- 테스트 커버리지를 높게 유지하기 위함

## ❗️Todo
- [ ] 
- [ ] 
- [ ]

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
[pytest와 pytest --cov github actions에 적용하는 페이지](https://docs.github.com/ko/actions/automating-builds-and-tests/building-and-testing-python)

**Comment by SongGwanSeok** [comment]
github action을 이용한 pytest 자동화 파일 
`.github/workflows/develop-pytest.yml`

``` yml
name: Run Pytest on Pull Request

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest
```
